//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunStoreDesktop.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GunStoreDesktop.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string AccentLabel {
            get {
                return ResourceManager.GetString("AccentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string AddEmployeeToolTipText {
            get {
                return ResourceManager.GetString("AddEmployeeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddItemText {
            get {
                return ResourceManager.GetString("AddItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item to receipt.
        /// </summary>
        internal static string AddItemToReceiptToolTip {
            get {
                return ResourceManager.GetString("AddItemToReceiptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountText {
            get {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal identification number.
        /// </summary>
        internal static string BuyerIdHintText {
            get {
                return ResourceManager.GetString("BuyerIdHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string BuyerLastNameHintText {
            get {
                return ResourceManager.GetString("BuyerLastNameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string BuyerNameHintText {
            get {
                return ResourceManager.GetString("BuyerNameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caliber.
        /// </summary>
        internal static string CaliberText {
            get {
                return ResourceManager.GetString("CaliberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color HEX value.
        /// </summary>
        internal static string ColorHexValueText {
            get {
                return ResourceManager.GetString("ColorHexValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string ColorText {
            get {
                return ResourceManager.GetString("ColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Sale.
        /// </summary>
        internal static string ConfirmSaleText {
            get {
                return ResourceManager.GetString("ConfirmSaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkLabel {
            get {
                return ResourceManager.GetString("DarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateHelperHintText {
            get {
                return ResourceManager.GetString("DateHelperHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateHintText {
            get {
                return ResourceManager.GetString("DateHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Employee.
        /// </summary>
        internal static string DeleteEmployeeToolTipText {
            get {
                return ResourceManager.GetString("DeleteEmployeeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string EmployeesLabel {
            get {
                return ResourceManager.GetString("EmployeesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EngLanguageText {
            get {
                return ResourceManager.GetString("EngLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string EspLanguageText {
            get {
                return ResourceManager.GetString("EspLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing item.
        /// </summary>
        internal static string ExistingItemText {
            get {
                return ResourceManager.GetString("ExistingItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string ExpirationDateHintText {
            get {
                return ResourceManager.GetString("ExpirationDateHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string FailedLoginCaption {
            get {
                return ResourceManager.GetString("FailedLoginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials..
        /// </summary>
        internal static string FailedLoginText {
            get {
                return ResourceManager.GetString("FailedLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        internal static string FieldsEmptyText {
            get {
                return ResourceManager.GetString("FieldsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterText {
            get {
                return ResourceManager.GetString("FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firearm.
        /// </summary>
        internal static string FirearmText {
            get {
                return ResourceManager.GetString("FirearmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        internal static string InStockText {
            get {
                return ResourceManager.GetString("InStockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters.
        /// </summary>
        internal static string InvalidCharactersCaption {
            get {
                return ResourceManager.GetString("InvalidCharactersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password contains forbidden characters.
        /// </summary>
        internal static string InvalidCharactersText {
            get {
                return ResourceManager.GetString("InvalidCharactersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string IsAdminText {
            get {
                return ResourceManager.GetString("IsAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        internal static string ItemIdText {
            get {
                return ResourceManager.GetString("ItemIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not in stock.
        /// </summary>
        internal static string ItemNotInStockText {
            get {
                return ResourceManager.GetString("ItemNotInStockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item type.
        /// </summary>
        internal static string ItemTypeText {
            get {
                return ResourceManager.GetString("ItemTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightLabel {
            get {
                return ResourceManager.GetString("LightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string ListEmptyCaption {
            get {
                return ResourceManager.GetString("ListEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item list is empty.
        /// </summary>
        internal static string ListEmptyText {
            get {
                return ResourceManager.GetString("ListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine size.
        /// </summary>
        internal static string MagazineText {
            get {
                return ResourceManager.GetString("MagazineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string ManufacturerText {
            get {
                return ResourceManager.GetString("ManufacturerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string ModelText {
            get {
                return ResourceManager.GetString("ModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item error.
        /// </summary>
        internal static string NoItemCaption {
            get {
                return ResourceManager.GetString("NoItemCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not exist.
        /// </summary>
        internal static string NoItemText {
            get {
                return ResourceManager.GetString("NoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string OrderButtonText {
            get {
                return ResourceManager.GetString("OrderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package size.
        /// </summary>
        internal static string PackageSizeText {
            get {
                return ResourceManager.GetString("PackageSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit not found.
        /// </summary>
        internal static string PermitNotFoundText {
            get {
                return ResourceManager.GetString("PermitNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit number.
        /// </summary>
        internal static string PermitNumberHintText {
            get {
                return ResourceManager.GetString("PermitNumberHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string PrimaryLabel {
            get {
                return ResourceManager.GetString("PrimaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item from receipt.
        /// </summary>
        internal static string RemoveItemToolTip {
            get {
                return ResourceManager.GetString("RemoveItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string SalesLabel {
            get {
                return ResourceManager.GetString("SalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettingsText {
            get {
                return ResourceManager.GetString("SaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string SrpLanguageText {
            get {
                return ResourceManager.GetString("SrpLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supplier selected.
        /// </summary>
        internal static string SupplierNotSelectedCaption {
            get {
                return ResourceManager.GetString("SupplierNotSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier must be selected.
        /// </summary>
        internal static string SupplierNotSelectedText {
            get {
                return ResourceManager.GetString("SupplierNotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string SuppliersLabel {
            get {
                return ResourceManager.GetString("SuppliersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string SupplierText {
            get {
                return ResourceManager.GetString("SupplierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        internal static string TotalPriceHintText {
            get {
                return ResourceManager.GetString("TotalPriceHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButtonText {
            get {
                return ResourceManager.GetString("UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists.
        /// </summary>
        internal static string UsernameAlreadyExistsText {
            get {
                return ResourceManager.GetString("UsernameAlreadyExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
    }
}
